spring:
  application:
    name: security
server:
  port: 8081
  
logging:
  file:
    name: "D:/Gaurav/Study/Programs/Backend Programs/microservice/microservice2/microservice_logs/security-service/application.log"
  pattern:
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false